// Code generated by "stringer -type=ElementKind"; DO NOT EDIT.

package gomd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EKHeading-0]
	_ = x[EKText-1]
	_ = x[EKBold-2]
	_ = x[EKItalic-3]
	_ = x[EKCodeSpan-4]
	_ = x[EKCodeBlock-5]
	_ = x[EKNewLine-6]
	_ = x[EKRule-7]
	_ = x[EKLink-8]
	_ = x[EKImage-9]
	_ = x[EKList-10]
	_ = x[EKQuote-11]
}

const _ElementKind_name = "EKHeadingEKTextEKBoldEKItalicEKCodeSpanEKCodeBlockEKNewLineEKRuleEKLinkEKImageEKListEKQuote"

var _ElementKind_index = [...]uint8{0, 9, 15, 21, 29, 39, 50, 59, 65, 71, 78, 84, 91}

func (i ElementKind) String() string {
	if i >= ElementKind(len(_ElementKind_index)-1) {
		return "ElementKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ElementKind_name[_ElementKind_index[i]:_ElementKind_index[i+1]]
}
