// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package gomd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KHeading-0]
	_ = x[KText-1]
	_ = x[KBold-2]
	_ = x[KItalic-3]
	_ = x[KCodeSpan-4]
	_ = x[KCodeBlock-5]
	_ = x[KNewLine-6]
	_ = x[KRule-7]
	_ = x[KLink-8]
	_ = x[KImage-9]
	_ = x[KList-10]
	_ = x[KQuote-11]
}

const _Kind_name = "KHeadingKTextKBoldKItalicKCodeSpanKCodeBlockKNewLineKRuleKLinkKImageKListKQuote"

var _Kind_index = [...]uint8{0, 8, 13, 18, 25, 34, 44, 52, 57, 62, 68, 73, 79}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
