// Code generated by "stringer -type=TokenKind"; DO NOT EDIT.

package gomd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TText-0]
	_ = x[TStar-1]
	_ = x[TUnderscore-2]
	_ = x[TLBracket-3]
	_ = x[TRBracket-4]
	_ = x[TLParen-5]
	_ = x[TRParen-6]
	_ = x[TBacktick-7]
	_ = x[TBang-8]
	_ = x[TDash-9]
	_ = x[THash-10]
	_ = x[TNewline-11]
	_ = x[TOLMarker-12]
	_ = x[TEOF-13]
}

const _TokenKind_name = "TTextTStarTUnderscoreTLBracketTRBracketTLParenTRParenTBacktickTBangTDashTHashTNewlineTOLMarkerTEOF"

var _TokenKind_index = [...]uint8{0, 5, 10, 21, 30, 39, 46, 53, 62, 67, 72, 77, 85, 94, 98}

func (i TokenKind) String() string {
	if i < 0 || i >= TokenKind(len(_TokenKind_index)-1) {
		return "TokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenKind_name[_TokenKind_index[i]:_TokenKind_index[i+1]]
}
